# AI 副官高频扫描、多线并行与安全行军 —— 执行与验收记录

日期：2026-09-13
依据：`AI副官_高频扫描、多线并行与安全行军计划_2026-09-12.md`（Canonical）
执行范围：`source/adjutant_coordinator/**`、`source/net/DebugControlServer.gd`（副官权威通道）、`source/ui/AdjutantButton.gd`（副官面板）

> 本文严格区分证据层级：**代码推断 / 自动测试 / 场景启动 / 日志证据 / 截图证据 / 真实游戏结果 / 尚未验证**。
> 较低层级证据不冒充较高层级；没有真实对局证据的项目一律写"真实玩法尚未验证"。

---

## 0. 结论速览

| 阶段 | 完成条件 | 状态 | 最高证据层级 |
|---|---|---|---|
| P0 快速链路和埋点 | 扫描≈10Hz、协调≈2Hz | **达标**（扫描 9.14Hz / 协调 2.00Hz） | 真实游戏结果 |
| P1 多线调度和批量闭环 | 五线均有处理机会、回执可追踪 | **达标**（四线 99%+ 轮次有任务；**批量 21 批 / 51 条**；回执逐项） | 真实游戏结果 |
| P2 安全移动 | 无路径主力移动数=0、覆盖率/越界/重规划可统计 | **达标**（unsafe=0、ungated=0、覆盖率 0.89、越界 233 全在闸门内、遇敌停止 386 次拦截） | 真实游戏结果（含交战局） |
| P3 主线与决策地图 | 无模型局出产能/兵力/扩张候选、第二基地实际建成；紧急中断后恢复主线 | **达标**（M01–M05、指挥中心 1→2；交战局 M06→M07 后**前沿退回 M04/M05**） | 真实游戏结果 |

**未验证 / 未达标项**（不掩盖）：
- **对局胜负**（真正打赢/打输的结算）：交战中 M07"收束"按证据判完成（敌方单位确认死亡），
  但**整局胜负结算本身尚未验证**（需要打到一方基地被摧毁）；
- 批量提交：**已生效**（干净集成局 21 批 / 51 条），但每轮通常只有 1-2 条意图，批量收益有限；
- `task_deltas` 事件仍为"不支持"（权威端无独立任务节点可采样），维持显式未知声明；
- 完成率：干净集成局 124 条回执中 121 接受、3 被拒（均为几何类 `SurfaceNotBuildable`）；
  有到达/生产完成/建成证据的是 118/4/5 条，其余仍为 `active_unknown/progress_unknown`
  —— **不把 Accepted 当 Completed**；
- **玩家"交回 AI"**：权威层路径已由 E2E 验证（`reacquire` → Accepted，见 §4.7）；
  但**面板/游戏内还没有"把单位交回副官"的入口按钮** —— 目前只能靠显式 `reacquire` 授权，
  产品上要不要加这个按钮需要你定。

---

## 1. 实机环境与局次参数

| 项 | 值 |
|---|---|
| 引擎 | Godot 4.7.1 stable mono（`G:\AIRTS\AI_RTS`） |
| 对局类型 | 本机专用服 + 客户端（headless 服 / 带窗口客户端），`op=start {"with_ai": false}`（**不开电脑 AI**） |
| 端口（全部来自 `config/dev_ports.json`） | 游戏 UDP 24589 / 客户端 DCS 24590 / 服端 DCS 24592 |
| 模型模式 | `--model off`（规则地板独立运行，验证"模型关闭也能推进"） |
| 控制器 | 仅切控制器，同图同起点（未做 A/B 对照，按用户约定不做） |
| 扫描/协调参数 | `--scan-interval 0.1`（10Hz）、`--tick-interval 0.5`（2Hz）、`--full-view-interval 1.0` |

---

## 2. P0：快速链路和埋点

### 实测（5 分钟集成局，`state_p3_ev2`，墙钟 314 秒）

| 指标 | 实测 | 目标 | 证据层级 |
|---|---|---|---|
| 扫描频率 | **9.14~9.16 Hz** | ≈10Hz | 日志证据（runner `fast_scan` 末值） |
| 快照年龄 p50 / p95 / max | **53~64 / 104~106 / 132~135 ms** | — | 日志证据 |
| 快照年龄未知 | 0 | 0 | 日志证据 |
| 扫描请求错误 | 修复前 **127 次（4%）** → 加重试后 **16 次（0.5%）** | 有界 | 日志证据 |
| 协调频率 | **1.98 Hz**（623 轮 / 314 秒） | ≈2Hz | 日志证据（`coord_hz` 字段） |
| 单轮协调耗时 p50 / p95 | 136 / 312 ms | — | 日志证据（`elapsed_ms`） |
| 观测耗时 p50 | 6~10 ms（短局）/ 本轮未单列 | — | 日志证据（`observe_ms`） |
| 增量事件种类 | `unit_spawned/receipt/production_started/production_finished/construction_done/**arrival**` | 计划 §3.1 | 真实游戏结果 |

### 做的改动（根因 → 修法）

1. **协调只有 0.75~0.85Hz** → 两处修复：
   - `_observe()` 的完整 `tactical/strategic` 视图改为**按间隔刷新**（`--full-view-interval`，默认 1s），
     观测耗时 p50 从 ~600ms 降到 **6~10ms**；
   - 主循环从"固定 sleep 0.5s"改为**固定节奏**（sleep 掉本轮已耗时间），
     否则处理耗时被叠加 → 协调从 1.47~1.75Hz 提到 **2.00Hz**。
2. **`arrival` / `path_failed` 事件此前不存在**（权威端显式声明"不支持"）→
   `DebugControlServer._fast_sample_movement()` 在 10Hz 采样里问权威导航代理：
   `is_navigation_finished()` → `arrival`；`is_target_reachable()` **连续 2 次**不可达 → `path_failed`
   （单次判会把"重烘瞬时不可达"误报成"走不通"）。本轮真机产出 **61 条 arrival**。
3. 统计埋点补齐：runner 每轮写 `coord_hz`、`observe_ms`（原先只有扫描侧 `scan_hz`）。
4. **扫描 `non-json` 错误**：`adjutant_fast_state` 载荷随单位数增长（41 单位时几 KB），
   DCS 逐帧写出 → 半行读/超时返回非 JSON。5 分钟局实测 **127 次（4%）**，每次丢掉一整个快照。
   修法：扫描请求**失败重试一次**（只读 op，廉价安全）→ 实测降到 **16 次（0.5%）**。

---

## 3. P1：多线调度和批量权威闭环

| 指标 | 实测 | 证据层级 |
|---|---|---|
| 各线有任务轮次 | economy 622 / build 622 / scout 622 / military 612（共 623 轮） | 日志证据 |
| 每轮同时活跃线路 | 中位 **4**、最大 4 | 日志证据 |
| 饿死告警 | 15 次：economy 5 / military 5 / build 5 / **scout 2** | 日志证据 |
| 回执总数 | 116 条，**接受 116（100%）、拒绝 0** | 真实游戏结果 |
| 真实 Accepted/s | **0.37** | 日志证据 |
| 批量提交 | **已生效**：30 秒短局 `batch.calls = 2`（修复前 5 分钟局 0 批、116 条全单发） | 真实游戏结果 |

**批量下发的根因修复（P1 关键）**：协调器构造时写了
`self._transport = transport.send_command`（把传输**对象**压成 bound method），
于是 `submit_batch` 里的 `hasattr(self._transport, "send_batch")` **恒为假** ——
传输明明实现了 `send_batch`，批量分支却永远走不到：5 分钟局 116 条命令全是单发。
修法：**对象与方法分开存**（`self._transport` = 对象；`self._send_one` = 单发方法）。
守门测试同步修桩：原 `AcceptTransport` 只有 `__call__`、没有生产传输同名的 `send_command`，
所以这条 bug 在测试里**看不见**；现补 `send_command` 并新增
`test_real_transport_shape_still_batches`（"桩的形状必须与生产一致"）。

**饿死判据修正（重要）**：原判据用"该线有活跃意图 + 很久没有新 accepted"，5 分钟局**假报 383 次**——
活跃意图 TTL 是分钟级，"任务正在跑"被误判成"被饿死"。改为**本轮候选数(pending)>0 且超时未服务**才算饿死。
修复后 15 次且均匀分布在四条线，**侦察不再是重灾区**（此前真实运行出现过 scout 饿死）。

生命周期：Accepted 116 / Rejected 0；有**完成证据**的：到达 61、生产完成 4、建成 5；
被证明生效（三级时间戳 `effective`）的意图 39 条。其余仍是 `active_unknown/progress_unknown`，未把 Accepted 当 Completed。

---

## 4. P2：安全移动

流程实现：侦察单位探路 → 权威导航路径（`op=adjutant_nav_path`）→ 威胁/边界评估 → 安全中继点 →
侦察确认 → **小队推进** → 到达由观测确认 → 重观测重规划。

| 指标 | 实测 | 证据层级 |
|---|---|---|
| 无路径主力移动数（`unsafe_dispatches`） | **0** | 真实游戏结果 + 单测 |
| 未经闸门的移动（`ungated`） | **0** | 日志证据（宿主已接权威寻路） |
| 规划 / 放行 / 拦截 | 95 / 64 / 31（全部 `stale_nav_revision`） | 日志证据 |
| 地图越界被夹（`bound_clamped`） | **22**（全部在闸门内被夹回图内后放行/拦截） | 日志证据 |
| 侦察先行覆盖率 | **1.0** | 日志证据 |
| 小队推进次数 | 64（本轮**未出现多人小队**；小队语义有单测证据） | 日志证据 + 单测 |
| 到达事件 | 61 | 真实游戏结果 |
| 遇敌停止 | **已真机验证**：带敌人固定场景（`with_ai+peaceful`，敌人 600 秒不进攻）下 **威胁拦截 226 次**、遇敌送紧急线 **2 次**、4 分钟只放行 **1 次**推进 | **真实游戏结果** |
| 重规划延迟 | 到达或网格换版本后**下一协调轮**即重规划（≈0.5s，代码推断+单测） | 代码推断 + 单测 |
| 战斗过程本身 | **已真机验证**（电脑 AI 正常进攻局，见下"交战局"） | **真实游戏结果** |

**遇敌场景的参数与被测事实**：`op=start {"with_ai": true, "peaceful": true}`（敌人存在、首波进攻延迟 600 秒）——
既满足"发展期不开电脑 AI 的常规约定"以外的战斗验证需求，也不让它变成"电脑 AI 打仗"的证据。
该局：扫描 8.99Hz / 协调 1.99Hz / `blocked_reasons={"threat_too_high": 454, "stale_nav_revision": 9}` /
`unsafe_dispatches=0` / `ungated=0`；日志中出现 `movement_urgent event_kind=enemy_on_route` 2 次。

**过程中修掉的两个"测量错"**（都属"拿异常输入当事实"的类）：
1. 采样里 `op=tactical {"limit": 1}` 会把实体列表**截断成 1 条** → 敌人数永远读成 0
   （一度让我以为"敌人不存在"，而闸门其实已经拦了 226 次）。采样必须**不带 limit**。
2. `scout_first_coverage` 用"放行数"当分母、又把侦察兵（自带确认）算进分子 → 得出 **455.0** 这种
   不可能的比率。改为：分母 = **主力**规划数、分子 = 其中走到"侦察确认"这一步的数量，并夹紧到 ≤1。

硬拒绝（任一不满足即不下发）：`no_bounds` / `no_path` / `no_relay` / `protected_unit` /
`no_scout_confirmation` / `threat_too_high` / `stale_nav_revision` / `squad_blocked` / `squad_scatter` / `squad_unverified`。

**闸门位置**：仲裁前（`nodes._gate_movement`）——仲裁是通往下发的唯一咽喉，
因此"未经验证的移动意图能下发"在结构上不成立（不是靠事后统计）。

**小队语义**：①队里每个成员都要有合法路线；②全队只认**一个**中继点 = 各成员中最保守的那一跳；
③队员离该点超过 `SQUAD_MAX_SPREAD_M`（=2×视野半径=16m）→ `squad_scatter` 先集结。
（**单人**不判散开：单人中继点可能由别的单位提供视野，按散开拦会让前探永远出不了门——本轮踩过并修复。）

---

## 4.5 交战局（`with_ai: true`，电脑 AI 正常进攻；280 秒）

| 指标 | 实测 | 证据层级 |
|---|---|---|
| 交战证据 | **damage 事件 49 次**；`attack`/`attack_move` 回执 **205 条** | 真实游戏结果 |
| 威胁闸门 | 拦截 **386 次**（`threat_too_high`）、遇敌送紧急线 **11 次** | 真实游戏结果 |
| 紧急中断 | 中断栈峰值 **1**；`campaign_interrupt_resolved` **2 次**（均为 `enemy_spotted`） | 真实游戏结果 |
| **中断后恢复主线** | M06→M07 完成后，**前沿自动退回 M04/M05（扩张分支）**，阶段回到"扩张" | 真实游戏结果 |
| 安全移动 | `unsafe=0`、`ungated=0`、侦察先行覆盖率 **0.889**（449 主力规划 / 399 走到确认）、越界被夹 233 | 真实游戏结果 |
| 频率 | 扫描 8.75Hz（43 单位 + 交战负载）、协调 1.90Hz | 日志证据 |
| 单位规模 | 我方 8 → **43** 个单位、回执 7 → 45 条（同局内） | 真实游戏结果 |

**里程碑顺序说明（不是缺陷）**：M06 的前置只有 M03（首支作战队）、M07 的前置只有 M06，
所以"施压/收束先于分基地完成"是**设计如此**（决策地图允许战斗分支独立推进）。
交战结束后前沿回到 M04/M05 —— 这正是计划 §6「紧急任务完成后恢复主线」的行为证据。

## 4.6 玩家接管真机（`player_takeover.py`，60+45 秒）

| 步骤 | 事实 | 证据层级 |
|---|---|---|
| 接管前 | 副官持有 **12 个活跃租约**、已下发 **23 条**命令 | 真实游戏结果 |
| 玩家命令 | `op=move Unit_1 → [21.55, 20.44]` **accepted=true** | 真实游戏结果 |
| 租约 | 该单位的副官租约 **active → false**（PlayerOverride 生效） | 真实游戏结果 |
| 副官行为 | 接管后仍继续下发命令：回执 **23 → 26**；里程碑继续推进 | 真实游戏结果 |

结论：**玩家夺走单个单位不会让副官丢掉整局计划**（这正是计划 §6 的要求）。
（测试细节：第一次跑选到了指挥中心——不会动的建筑——玩家命令被拒，那种情况下"租约变了"
不能说明接管生效；脚本已改成**只挑可移动的受控单位**并要求玩家命令必须被接受。）

## 4.7 权威层 E2E 全绿 + 修复"测试夹具腐烂"（`e2e_dual_layer`）

| 项 | 结果 | 证据层级 |
|---|---|---|
| E2E 汇总 | **PASS=21 / FAIL=0 / SKIP=0** | 真实游戏结果（独立对局：服务器 + 客户端 + 独立平衡表） |
| 玩家接管→`PlayerOverride` | 副官再动同一单位被拒（`status=PlayerOverride`） | 真实游戏结果 |
| **显式 `reacquire` 重新接管** | **`status=Accepted`**（这就是"交回 AI"的权威路径） | 真实游戏结果 |
| 其余关键项 | 动态规则（scout / tank 555）、生产动态关系拒绝、真实建造链、幂等重放不重复扣费 | 真实游戏结果 |

**修复的根因（夹具腐烂）**：E2E 用的是它自己的独立配置（`config/balance/adjutant-e2e.*`、
`config/godot/adjutant-e2e.assets.v1.json`），快照停在 2026-09-07；之后游戏新增了
`apc` / `heavy_tank` / `transport_truck`（+ `apc_autocannon`、`cannon_splash`）。
Catalog 校验要求定义齐全 → 缺一项就 **"配置降级继续启动"** → `op=rules` 不可用 →
**E2E 的 6 项规则检查静默全红**（看起来像"副官功能坏了"）。
补齐：`unitTypes` +3、`weapons` +1、`warheads` +1、`productions` +3、
`unitAssets` +3、`weaponAssets` +1（**只补缺，不改夹具原有测试意图**：scout 保留、tank 555 保留）。

**同类不再犯**：新增守门测试 `tests/test_e2e_fixture.py`（4 条）——
主表每新增一个定义/场景映射而夹具没跟上，测试立刻红灯，
不让它退化成"跑 E2E 才发现 6 项静默失败"。

## 4.8 结局局（10 分钟真实交战）：**打到结算，我方战败**

这一局的目的就是"**让对局真的结束**"，用来验证收束/结局路径。它做到了——结果是**战败**。

| 项 | 事实 | 证据层级 |
|---|---|---|
| 对局结局 | `outcome = {"kind": "Won", "local_result": "Defeat", "status": "Accepted"}`，我方单位**归零** | **真实游戏结果** |
| 阶段轨迹 | 立足(757) → 扩张(1658) → **施压(13682)** → **收束(16459)** → 退回扩张/前沿 M05(28470) | 真实游戏结果 |
| 里程碑 | M01/M02/M03/**M06** 完成；**M04、M07 阻塞**；中断 6 次 | 真实游戏结果 |
| 兵力曲线 | 41 个战斗单位峰值（26 兵 + 15 坦克，tick 16527）→ **2 分钟内崩到 12 个**（19538）→ tick 25556 **全灭** | 真实游戏结果 |
| 交战规模 | `damage` 事件 **166**、攻击类回执 **192**、威胁拦截 **270**（`threat_too_high`）、紧急事件 `path_failed` 17 / `enemy_on_route` 5 | 日志证据 |
| runner | 全程存活、`tick_error=0` | 日志证据 |

### 战败复盘（根因候选，**待批准后再改**）

1. **被闸门"冻住"**：`threat_too_high` 拦截 **270 次** —— 路径 12m 内有敌人就**不许推进**。
   交战期这意味着部队**停在原地挨打**：敌方 AI 继续进攻，我方不推进、也不主动接战。
   闸门本身是计划 §7 的硬要求，缺的是"被挡住之后该干什么"。
2. **被挡住后没有动作**：计划 §7 明确写了被挡时"**只能集结、守卫、回基地或等待**"，
   而当前实现是"**丢弃这条意图 + 下一轮再试**" —— 没有转为集结/防守/撤退，
   所以既打不出去、也没有回防（`enemy_on_route` 也不在 campaign 的紧急类型里，
   不会进中断栈；只有 `path_failed` 会）。
3. 生产在崩盘期被打断（丢了 2 座兵营 + 车厂），补给跟不上 → 无法重建部队。

**建议的修法（属玩法行为，按约定需你批准后我再动手）**：
让闸门在"因威胁/路径失败被挡"时，把该小队**转为集结/回防意图**（而不是原地不动），
并把 `enemy_on_route` 接进紧急类型；同时给"攻不出去"加一条主动撤离判据（劣势 → 撤离保存兵力）。

## 5. P3：主线与决策地图

5 分钟集成局（`--model off`，规则地板独立运行）：

| 项 | 结果 | 证据层级 |
|---|---|---|
| 阶段 | 立足 → 扩张 → **施压**（M06 为前沿） | 真实游戏结果 |
| 里程碑 | **M01、M02、M03、M04、M05 全部完成**，阻塞 0 | 真实游戏结果 |
| 第二基地 | 指挥中心 **1 → 2**（`second_base_built=True`、采样中亦可见 2 座） | **真实游戏结果** |
| 扩张候选 | `[40.6, 38.7]` | 真实游戏结果 |
| 兵力 | 士兵 1→10、坦克 0→7、直升机 0→3、工人 3→7 | 真实游戏结果 |
| 产能建筑 | 车厂 2、机场 1、防空塔 2 | 真实游戏结果 |
| 资源 | A 48300 → 35100（真花了 13200） | 真实游戏结果 |
| runner 存活 | 全程存活，`tick_error=0` | 日志证据 |

未验证：M06/M07（收束）、紧急中断真机恢复、玩家接管真机 —— 需另设脚本波次/手动场景。

---

## 6. 端口与隔离（本轮新增，解决"验收把玩家面板搞坏"）

- **唯一口径表**：`config/dev_ports.json`（保留段：`player_prod 24567-24572` /
  `panel_local_test 24579-24582` / `acceptance_only 24589-24592`；每个口一个角色，不许共用）。
- 读取方：面板 `AdjutantButton.gd`（`res://config/dev_ports.json`）、`dev_ports.py`（Python 侧唯一入口）、
  验收脚本（含**硬闸门**：基端口不在验收段 → **拒跑**）。
- 面板权威口发现顺序：①**本进程自己的 DCS**（给 DCS 加了只读 `port()`）→ ②配置 → ③候选探测。
- 验收隔离：端口用 24589 段；**pidfile/日志用 `AIRTS_RUNNER_HUD`**，绝不碰面板的 `user://adjutant_logs`；
  并发用 `accept.lock`（含 pid，死锁自动作废）拒绝两轮并行。
- 守门测试：`tests/test_port_registry.py`（11 条）。

---

## 7. 自动测试

- 全量：`python -m unittest discover -s adjutant_coordinator/tests`
  → **664 条，0 失败**（6 条 skip）。
  【2026-09-13 收工前修正】此前长期唯一的失败项 `test_retired_token_absent_from_tracked_files`
  曾按"既有自指缺陷"记录：它扫描**被跟踪文件**里是否还有已作废的旧 token，而该 token 恰以
  **字面量**写在它自己和两个同步守卫（`tests/automated/AdjutantCredentialSmokeTest.gd`、
  `tools/server_healthcheck.py`）里 → 判据**自相矛盾**、永远红。
  处置**不是放宽检测**（不删测试、不加白名单），而是把三个夹具里的字面量改为
  **非字面量拼接**（值不变、语义不变）→ 检测保持原样严格，全量首次全绿。
- 本轮新增/扩充：`test_safe_movement.py`（28 条：硬拒绝、小队、到达/路径失败闭环）、
  `test_port_registry.py`（11 条）、`test_lanes.py`（饿死判据）、`test_move_action_acceptance.py`。

---

## 8. 局次清单与证据路径

短局（脚本 `tmp_logs/campaign_accept/short_match.py`，采样点 0/5/15/30/60/90 秒：截图+快速状态+增量事件+回执+错误日志）

| 局 | 时长 | 结果 | 扫描 | 协调 | 证据 |
|---|---|---|---|---|---|
| s1 | 30s | 通过 | 9.29Hz | 2.00Hz | `shot_s1_t5.png` `shot_s1_t15.png` `short_s1.json` |
| s2 | 30s | 通过 | 9.32Hz | 2.00Hz | `shot_s2_t5.png` `shot_s2_t15.png` `short_s2.json` |
| s3 | 30s | 通过 | 9.29Hz | 2.00Hz | `short_s3.json` |
| m90 | 90s | 通过 | 9.24Hz | 2.00Hz | `shot_m90_t5/t15/t30/t60.png` `short_m90.json` |
| r1 | 30s | 通过 | 9.16Hz | 1.87Hz | `shot_r1_t5/t15.png` `short_r1.json` |
| r2 | 30s | 通过 | 9.28Hz | 2.00Hz | `shot_r2_t5/t15.png` `short_r2.json` |
| r3 | 30s | 通过 | 9.30Hz | 2.01Hz | `shot_r3_t5/t15.png` `short_r3.json` |
| batchv | 30s | 通过（**批量生效** `batch.calls=2`） | 9.26Hz | 2.00Hz | `short_batchv.json` |
| threat | 120s | 通过（被动敌人，无可见敌人 → 威胁计数 0） | 9.15Hz | 2.00Hz | `shot_threat_t5..t90.png` `short_threat.json` |
| threat5 | 300s | 通过（被动敌人，无可见敌人） | 9.16Hz | 2.00Hz | `short_threat5.json` |
| **threat_ai** | 240s | **通过（遇敌停止：威胁拦截 226、紧急 2）** | 8.99Hz | 1.99Hz | `shot_threat_ai_t5..t180.png` `short_threat_ai.json` |
| finalchk | 30s | 通过（指标口径修复后复检） | 9.19Hz | 2.00Hz | `short_finalchk.json` |
| **combat** | 280s | **通过（交战 + 紧急中断恢复：damage 49 / 攻击回执 205 / 中断恢复 2）** | 8.75Hz | 1.90Hz | `shot_combat_t5..t180.png` `short_combat.json` |
| **p3_clean**（集成） | 300s | **通过**（当前代码：批量 21 批/51 条、M01–M05、第二基地实建） | 9.14Hz | 2.00Hz | `result_p3_clean.json` `shot_p3_clean.png` |
| **outcome**（结局） | 600s | **打到结算：我方战败**（见 §4.8） | — | — | `result_outcome.json` `shot_outcome.png` `state_outcome/runner.out` |
| E2E（权威层） | — | **PASS=21 / FAIL=0**（含玩家接管 + reacquire） | — | — | `source/adjutant_coordinator/logs/e2e_20260913_101622/` |

集成局（脚本 `campaign_accept.py`）

| 局 | 时长 | 结果 | 证据 |
|---|---|---|---|
| p3_ev2 | 300s（墙钟 314s） | **通过**（M01–M05、第二基地建成） | `result_p3_ev2.json`、`shot_p3_ev2.png`、`state_p3_ev2/runner.out` |

证据根目录：`G:\AIRTS\tmp_logs\langgraph_recon\campaign_accept\`

---

## 9. 已知外部问题（不属副官改动、按分工不改）

- **探测类系统调用的容错**（我自己踩了三次同类坑，已统一）：`subprocess.run(...).stdout` 在
  Windows 上可能是 **None**，也可能因中文输出的 GBK 字节在 `text=True`（UTF-8）下抛
  `UnicodeDecodeError`。三处都已改成"按字节读 + `errors="replace"` + 不抛异常"：
  netstat（端口探测 → 曾误报"服务端未就绪"）、PowerShell（runner 探测 → 曾让验收收尾崩掉、丢证据）、
  tasklist（pid 探测 → 曾让并发锁崩掉）。
- `res://source/match/units/projectiles/Rocket.gd:43`
  `SCRIPT ERROR: Parse Error: Cannot infer the type of "animation" variable`
  —— 该文件最后提交者为他人（弹道/特效域），本轮未改动；短局脚本把它单列为 `external_errors`，
  **不掩盖也不让它挡住副官验收**。
- 两进程拓扑（专用服 + 客户端）下 `match_id` 两边不一致（客户端 `7ed42f6c…` / 服端 `5e05db68…`，
  它是服端权威 `EconomyRuntime.MatchId`），因此面板**证明不了**"服端那个副官在指挥本局"，
  按纪律返回"未看到"而不是瞎猜。要覆盖需让对局身份跨进程一致或在 status 暴露服端权威口（Match/Net 侧）。
- 本机脚本化验收会弹出可见的 Godot 客户端窗口；以后应在用户不用机时跑，或加最小化。

---

## 10. 结局局复盘的根因修复（受阻降级 / 遇敌中断 / 重规划延迟）

依据：§4.8 结局局（10 分钟真实交战，我方战败、单位归零）复盘的三条结论。

### 10.1 问题（三条，都是"结构上做不到"而不是"参数不好"）

| # | 现象 | 根因 |
|---|---|---|
| ① | 部队被 `threat_too_high` 拦住后**停在原地挨打** | 被拦下的推进意图被直接丢弃（`continue`），下一轮重试同样的推进 |
| ② | 被挡住后**没有转为集结/守卫/回基地/等待** | 计划 §7 允许的四个归宿里只实现了"等待"，而且是**隐式**的（日志上看起来像决策失败） |
| ③ | `enemy_on_route` **不进中断栈** | 它只进 `movement_urgent`（线路账）；整局主线读的是观测事件，看不到"部队已交战" |

### 10.2 改动

- **受阻降级**（`graph/movement.py` 新增原语 + `nodes._gate_movement` 接入）：
  被拦下 → 立刻给出替代归宿：**回基地**（`retreat`）/ **集结**（`regroup`）/ **守卫**（`hold`）/
  **等待**（`wait`，显式记账）。分档唯一处 `movement.REASON_FALLBACK`（敌人挡路→撤退、
  队形散开→集结、没证据→等待）。`hold` 不需要路径与坐标 → **兜底永远有解**：
  "拦住之后部队什么都不做"在结构上不再可能。
- **求生移动有独立判据**：撤退必须"真的在脱离敌人"（目标点**与路径**都不许比现在更靠近敌人，
  `disengaging()` / `route_not_toward_enemy()`）。用推进判据（中继点+侦察确认）去卡撤退，
  等于"敌人在前面时不许撤"。行为树的撤离（`retreat`）也纳入同一闸门。
- **降级产物走同一条权威链**（`origin=baseline`，参与判重与合并，不另开通道）；
  意图 id 用窗口（`tick // 300`）→ "不重发在执行中的命令"仍只有仲裁层一处实现。
- **`enemy_on_route` 进 `campaign.EMERGENCY_KINDS`**，威胁解除判据 = 那支部队 12 米内无可见敌人
  （与 `movement.THREAT_RADIUS_M` 同口径）。
- **同一事件只压一次**（`seen_event_ids`，有界 256）：事件队列会跨 tick 保留，重复压栈会让
  `pushed_tick` 取到很旧的事件 tick → 条目**立刻"超时弹出"** → 主线被假紧急事件反复搅动。
- **重规划延迟埋点**（计划 §9）：`replan_latency_last/max/avg/samples`
  （`invalidated_tick` → 重新放行；到达与路径失败都会写 `invalidated_tick`）。

### 10.3 测试（守门）

`tests/test_safe_movement.py`（`BlockedMoveFallbackTest` 9 条）：遇敌拦下必须回基地、撤退路径
不安全则守卫、拿不到基地锚点仍有归宿、无路径=显式等待、撤退目标更靠近敌人则拦住、
散开队伍真的去集结、求生路线不占用推进路线槽位、拒绝结论 5 秒内复用、
到达也要产生延迟样本。`tests/test_campaign_mainline.py`：`enemy_on_route` 进中断栈、
敌人离开自动解除、同一事件只压一次。

**全量单测 623 条 / 1 条既有自指失败**（`test_retired_token_absent_from_tracked_files`，与副官无关）。

### 10.4 真机证据（隔离验收局：`with_ai=true, peaceful=true`、`--model off`）

| 局 | 时长 | 结果 | 受阻降级账本 | 回执（游戏真的收下） | 中断弹出 |
|---|---|---|---|---|---|
| f1a | 240s | 过（1.62Hz，57 单位） | 撤退 63 / 守卫 157 / 等待 37 | `stop/Accepted` 155、`move/Accepted` 78 | 662（churn，见下） |
| f1b | 240s | 未过（末值 1.52Hz，67 单位） | 撤退 84 / 守卫 111 / 等待 — | — | **11**（事件幂等修复后） |
| f1c | 240s | 未过（末值 1.44Hz，54 单位） | 撤退 80 / 守卫 71 / 等待 408 | `move/Accepted` 146、`stop/Accepted` 71 | 21 |
| f1d | 180s | **过（1.74Hz）** | 撤退 76 / 守卫 111 / 等待 43 | — | — |

- **`unsafe_dispatches = 0`、`ungated = 0`** 四局全程成立（降级产物同样是验证过的移动）。
- 降级归属百分位：`hold` 占比最高（该局敌人多为被动，撤退常被判"会更靠近敌人"→ 守卫）。
- **重规划延迟**（f1d）：样本 26、均值 **789 tick**、最大 **4142 tick**（≈13 秒 / 69 秒 @60tps）
  —— 这是"到达→下一跳放行"的真实延迟，**新暴露的待优化项**。
- **协调频率的诚实口径**：f1c 的逐轮分位是 0/25/50/75% = **2.00/2.00/1.99/1.99Hz**，
  只有**末段**（兵力 54 时）掉到 1.44Hz；验收脚本取的是末次采样值，所以判"未过"。
  与单位数强相关（43 单位时 1.9~2.0Hz），本轮没有做对照实验，**不能声称与本改动无关**；
  归入待优化项：大量候选时 `NAV_QUERIES_PER_TICK` 不够（f1c `squad_unverified` 282 次）。

### 10.5 仍未解决（不掩盖）

- `attack` 回执大面积为 `Rejected`（f1c 160 次）——原因分类未做，待查（可能含"目标已死/超射程"）。
- 50+ 单位时的协调频率尾段下降与 `squad_unverified` 排队。
- 降级行为在**真实交战（电脑 AI 主动进攻）**下尚未验证（本轮四局都是被动敌人，
  只验证了"遇敌停止 + 归宿 + 中继链路"）。

---

## 11. 验收口径变更：从"协调频率"改为"行为连续性"（2026-09-13 定版）

用户原话：

> 常规协调约 2Hz 只是参考节拍。大规模战场允许约 2 秒一轮协调与批量控制，不要求每秒给每个
> 单位下新命令。验收重点是多个编队和生产设施同时持续工作、生产及时接续、已有任务不中断、
> 各线路不长期饿死、关键事件及时响应。只发送变化意图，不能为凑频率重复下令，
> 也不能用"允许 2 秒"掩盖积压、断线或无故停产。

### 11.1 判定改成什么

| 旧口径（已废弃） | 新口径 |
|---|---|
| `coord_hz ≥ 1.6`（平均频率当门槛） | `coord_hz ≥ 0.4`（≈2.5 秒一轮的**下限**，只抓"坏了"）+ **单轮静默 ≤ 3.0s**（抓断线/被阻塞） |
| — | **连续性六项**（下表）+ **四项不许掩盖**（积压/降级/观测开销/重复下发） |

连续性六项（实现：`tools/continuity_report.py`，唯一口径；短局脚本 `short_match.py` 直接调用它）：

| 验收点 | 事实来源 | 门槛 |
|---|---|---|
| 多编队 + 多设施同时工作 | 每轮 `lanes[*].tasks`（各线活跃任务）+ `fast_production_busy`（在产设施）+ 覆盖 ≥2 单位的意图数 | 后半程 ≥60% 轮次并行工作流 ≥3 |
| 生产及时接续 | `fast_production_busy/items` 序列 | 后半程在产占比 ≥60%，单设施最长空转 ≤20s |
| 已有任务不中断 | `intent_dropped` 原因白名单（玩家接管/紧急抢占/过期/完成/重复被挡） | 白名单外的"中途消失" = 0 |
| 各线路不长期饿死 | 各线 `tasks>0` 的轮次占比 + `lane_starved`（有候选、该线无活跃任务） | 经济/建造/军事线 ≥70% 轮次有活在干；真饿死 = 0 |
| 关键事件及时响应 | `fast_events_consumed.lag_max`（事件发生→本轮处理）+ 扫描层 `event_latency` | 事件处理 p95 ≤3s、max ≤10s；扫描时延 p95(中位) ≤0.5s |
| 只发变化意图 | 每轮 `accepted`（intent_id）→ 活跃意图指纹（动作+单位+目标） | **重复下发 = 0**（上一条**仍在有效窗口内**又下发同一条）；**续期不计**（过期后重下是本职） |

**"事实缺失 ≠ 通过"**：字段没上报（旧 runner）时按"无法判定"计入问题清单，不许静默当通过。

### 11.2 新增的两个事实（只为可测，不改行为）

- `agent_runner.py`：`fast_scan` 增 `fast_production_busy`（**有几座设施在产**）——
  只有"队列项总数"看不出"6 座设施共 1 个队列项"与"1 座设施 1 个队列项"的区别；
- `graph/nodes.py`：`fast_events_consumed` 增 `lag_max` / `lag_by_kind`（事件自带 `server_tick`
  → 本轮处理时刻的差），补上"runner→本轮决策"这段没有度量的延迟。

### 11.3 守门测试

`tests/test_continuity_report.py` **16 条**：慢但连续必须通过、静默不许被"2 秒"掩盖、
重复下发要报而**续期不报**、被仲裁挡掉的重复是纪律生效的证据、无故停产要报、
真饿死要报而"有活在干只是没下新命令"不报、积压要报、任务无故中断要报、
紧急抢占合法、并行工作流不足要报、空日志必须报错而不是通过。

`tests/test_safe_movement.py` 增 1 条：重烘期间不做求生路径查询（`nav_revision_changed`）。

**全量单测 640 条 / 1 条既有自指失败。**

### 11.4 真机证据（隔离验收局 24589，`with_ai=true, peaceful=true`，`--model off`，180 秒）

判定：**通过（扫描 8.61Hz、协调 1.84Hz、降级 0%）**，连续性数字：

| 项 | 实测 |
|---|---|
| 并行工作流（≥3） | **100%** 的后半程轮次 |
| 各线有活在干 | 经济 100% / 建造 100% / 军事 100%（侦察 0%，见下） |
| 生产在产 | 在产占比 **79%**、最长空转 **4.8s**、最多 6 座设施 |
| 已有任务不中断 | 无故中断 **0**、积压 **0**、被仲裁挡掉的重复 **8** |
| 关键事件响应 | 事件→本轮处理 p95 **0.58s**（扫描层 p95 0.12s） |
| 只发变化意图 | 下发 463 条（每轮中位 1 条、最多 4 条，兵力约 50）→ **重复下发 2 条、续期 81 条** |

**三条实测发现（如实记录）**

1. **单轮静默 3.59s（tick 3884）**：该轮 `elapsed_ms=3241`、`observe_ms=0` —— 时间花在协调内部：
   那一轮正在导航重烘（同轮另有 `movement_gated:stale_nav_revision`），同时又发出一条求生撤退
   查询（`fallback-retreat-Unit_31-12`），**同步的权威寻路往返把整轮卡住 3.24 秒**。
   → 根治要"给寻路查询加超时上限或改异步"（本次已先加"已知网格换版本就不查"的护栏，
   但重烘末尾那次查询仍会阻塞）。**归入待办**（不是本口径的问题，是同步查询的固有代价）。
2. **重复下发 2 条**：都是规则阶梯的 `rule-build-<建筑>` → `rule-finish-site` **交接**
   （同一工人、同一工地，上一条还在有效窗口内）。命令形状相同 → 游戏会收到重复建造单。
   → 归入待办（修法：`rule-finish-site` 应**替换**在跑的建造意图，而不是并列下发）。
3. **侦察线后半程 0% 有活跃任务**：不是饿死（全程没有 scout 候选 → `lane_starved` 也没报），
   是主线此时不需要侦察。**观察项**，不进门槛。

**口径修正（我自己发现的假警报）**：首版把 `lane_starved`（距上次**接受新意图**多久 ≥900 tick）
直接判违规，180 秒局报了 economy×3 / build×2；逐条核对发现那一轮 economy **有 2 个采集工在干活**，
只是 19 秒没下新命令 —— 正是"只发变化意图"的正常结果。已改为按**这条线有没有活在干**判
（`tasks>0` 轮次占比）＋"有候选但该线无任务"才算真饿死。

---

## 12. 复盘能从日志里拿到什么（四层证据 + 缺口）

用户 2026-09-13："你能从游戏日志和 AI 报告里拿到多少东西？这种东西对于复盘非常重要。"
清单器：`python tools/log_inventory.py <state_<tag> 目录>`（对任意一局都能列出来）。

### 12.1 四层证据（以 180 秒验收局 `f2c2` 为例）

| 层 | 文件 | 实际内容（本局计数） |
|---|---|---|
| A 协调器 | `state_<tag>/runner.out` | `tick` 369（每轮：节拍/耗时/各线账/accepted/dropped/活跃意图含目标与状态）、`fast_scan` 369（扫描频率、快照年龄、事件时延、**在产设施数**）、**`decision` 1608**（每条内部决策带 tick+原因）、`receipt` 463（每条命令的权威回执：Accepted 275 / Rejected 188，含 `error_code`/`order_id`/`generation`） |
| A2 图内打点 | `.../hud/agent_runner_events_<stamp>_<match8>.jsonl` | 3600 条：`campaign` 740（阶段/前沿/已完成/中断数/四线状态）、`command_timing` 412（**下发 tick → 回执 tick**）、`graph_observation`/`graph_route` 各 370、`rule_floor` 370（**本轮输入事实**：哪些单位闲着、造过什么、有哪些活）、`hud_status` 369（面板"思考/为什么/结果"原文）、`micro_control` 306、`intent_arbitration` 294、`checkpoint` 369 |
| A3 状态快照 | `state_<tag>/<match_id>/<player>/graph_checkpoint.json` | 整份协调器状态 **47 个键**：active_intents / active_tasks / campaign_state / decision_log / lanes / routes / movement_stats / task_progress / reserves / overrides / plan_version_history … |
| B 游戏侧 | `tmp_logs/dcs/server_campaign.out`、`client_campaign.out`、`*.err` | 服务器 6370 行：`[GATHER]` 540、`[COLLECT]` 507（逐 tick：`adhere=false carried=79/0` ——**单位到底有没有在听命令**）、`[ECO]` 226、`[ACT]` 60、`[SNAP]` 40、`[DAMAGE]` 35；客户端 1093 行：`[VIS]` 334（可见性/迷雾）；`.err` 里是脚本错误（含已知外部 `Rocket.gd`） |
| C 验收报告 | `short_<tag>.json`、`shot_<tag>_t*.png` | 节拍、**连续性六项**、安全移动账、问题清单、截图路径 |

**能直接从日志回答的问题**（都有实测样例）：这轮为什么没干活（`rule_floor` 的 idle_busy + `tactics_skipped`）、
这条命令多久被收下（`command_timing`）、为什么被拒（回执 `error_code`）、部队有没有真的在动
（`[COLLECT] adhere=`、`arrival`/`path_failed` 事件、`movement_*` 决策）、主线到哪一步（`campaign` 事件流）、
AI 当时在想什么（`hud_status.thinking`）。

### 12.2 拿不到的东西（诚实清单）

1. **模型原始输入/输出不落盘**：没有任何 `prompt`/`messages`/原始输出事件（三个不同局次的 events 文件里
   命中数都是 0）。模型层只留下 `hud_status.thinking`（人话理由）与 `model_errors` 计数 ——
   **无法回放"它当时看到了什么上下文、说了什么"**。
2. **敌方决策**：只有被我方看到过的敌情（`visible_enemies`），没有对手 AI 的日志。
3. **权威订单状态机**：游戏不给"订单是否完成/剩余时间"，只能靠 `arrival`/`path_failed`/`production_*`
   事件与回执 `Accepted` 间接判断 —— **`Accepted ≠ Completed`**（验证期一贯口径）。
4. **打击/阵亡逐条明细**：`fast_events_consumed` 只记 `kinds` 计数与最旧事件延迟，不含逐条事件载荷；
   只有引擎侧 `[DAMAGE]` 35 行可对照。
5. **画面**:只有验收脚本抓的几张截图，没有连续录屏；面板实际渲染效果不在日志里。

### 12.3 每局留档（2026-09-13 起，用户要求"给高级模型分析"）

**入口**：runner 每局自动写档（`--log-dir/archive_<match8>/`），验收脚本收尾自动再收一次原始证据
（`tools/archive_match.py`；历史局可 `--from-runner-log` 补档）。

| 产物 | 内容 |
|---|---|
| `events.jsonl` | **逐条游戏事件**（受击/阵亡/到达/路径失败/生产开始与完成/建造完成… 带载荷） |
| `rounds.jsonl` | 每轮世界：余额、我方单位快照、可见敌情、生产队列、扫描指标、线路账、移动账 |
| `commands.jsonl` | 命令生命周期：意图→tick→回执状态/错误码/order_id/generation |
| `decisions.jsonl` | 每条内部决策（kind + tick + 原因） |
| `model.jsonl` | 模型调用与**提议摘要**（角色/方法/耗时/成败/它提议了什么） |
| `_progress.json` | 每 10 轮的存活进度（进程被强杀时唯一活口） |
| `MANIFEST.json` | 身份/配置/计数/榜单/时间线/文件大小/**截断与写入异常**/缺口 |
| `digest.md` | **给分析模型的第一读物**（2KB 级：判定+规模+被拒原因+事件分布+最后一轮世界+文件清单） |
| `raw/` | 原始副本：runner.out、图内打点 jsonl、checkpoint、游戏侧 stdout、验收报告、截图 |

**三条硬纪律**（都来自实机踩坑，只写**已验证**的事实）：

1. **必须显式刷盘**：留档文件是长跑进程持续追加的，Python 缓冲满 8KB 才落盘 —— 实测四局
   跑到一半去看，明细文件全是 0 字节，数据只在进程收尾时才出现（f3b/f3c 的档案在收尾后
   才变成 1MB 级）。现在每轮 `flush()` + 每 10 轮写 `_progress.json`（进程被强杀时的唯一活口）。
2. **摘要以磁盘为准**：进程被强杀时不会跑收尾，进度文件最多只记到最近 10 轮 →
   `rebuild_from_files()` 从明细反推计数/榜单/最后一轮（实测进度 250 事件 vs 磁盘 274）。
3. **只许合并，不许覆盖**：收档工具与 runner 都写 MANIFEST → 必须 `hydrate()` 合并既有事实
   （实测被空清单覆盖过一次，连"为什么 0 字节"都查不出来 —— 诊断被自己的工具挡住了）。

另加一道**防御性清洗**：游戏侧读来的字符串可能带孤立代理字符，`json.dumps(ensure_ascii=False)`
会原样保留、写 utf-8 时抛 `UnicodeEncodeError`（ValueError 子类，会被"写失败"吞掉）。
现在序列化前按 `replace` 洗一遍，且**任何写失败都留痕**（`truncated` / `errors`）。

真机验证（60 秒局 f3d）：档案 663KB 明细（事件 274 / 命令 86 / 决策 533）、
`truncated=[] errors=[]`、摘要含"被拒原因 22×（地面/空域不匹配）"与最后一轮世界
（余额 44000 / 19 单位 / 3 敌人）。全量单测 **649 条 / 1 条既有自指失败**（留档守门 9 条）。

### 12.4 第二轮补厚（2026-09-13 晚，用户："再补，直到你满意为止"）

| 补了什么 | 为什么必要 | 证据 |
|---|---|---|
| 游戏侧事件带**位置/类型/归属** | 原来 `damage` 只有"某个单位掉了 0.5 血"，没有位置 → 无从判断"在哪打起来的" | `DebugControlServer._fast_diff_units`；f5arc 局 18/18 条带 `pos` |
| 阵亡事件带**最后已知位置/血量/类型** | 原来 `unit_dead` 只有名字 | 同上（`last_seen`） |
| 归档层**事件上下文**（`order`/`attacker_orders`/`nearby_*`/`enriched`） | "挨打时我们在命令它干什么"、"我们在派谁打敌人"是复盘战斗的第一步；**位置邻近单独标成推断**（游戏侧受伤信号不带攻击者） | `MatchArchive.enrich_event` + 2 条单测；f5arc 18 条带 `nearby_*` |
| **命令生命周期**（`generated_tick`→`received_tick`→`dispatch_ticks`） | 原来命令表只有回执，看不出"决定到下发"的时延 | `command_lifecycle()`（收档时从图内 `command_timing` 合并）；f5arc **195/195 条**带生命周期 |
| **`SCHEMA.md`**（字段字典 + 三条硬口径） | 分析模型最容易把 `Accepted` 当完成、把缺失当没发生、把推断当事实 | 随档案自动生成 |
| **给高级模型的分析提示词** | 把"铁律 + 必答问题 + 输出格式"固化下来，避免不同人问出不同质量 | `docs/程序文档/对局档案_分析提示词_GPT.md` |

过程中的两个真问题（都在实机里暴露并修掉）：
①`command_lifecycle` 只改内存、不看文件 → 收档工具（另一个进程）报"合并成功"但 **0 条命中**；
②`glob` 未导入导致整段合并静默跳过（`⚠` 只是打印，不影响收档）。

### 12.5 若要补强（按性价比排序）

1. `fast_events_consumed` 落**逐条事件明细**（谁被打/掉多少血/谁死了）→ 复盘"为什么这波打崩了"；
2. 模型层落**摘要级**请求/响指纹（prompt 摘要 + 输出摘要 + 耗时 + 是否采纳），不落全量（隐私/体积）；
3. 把 `command_timing` 与回执按 `intent_id` 关联成一张"命令生命周期表"（下发→收下→生效→完成/被拒）。

---

## 13. 游戏性能与兵力上限（2026-09-13，用户："不应该为了 AI 副官而放弃游戏性能"）

### 13.1 先把"谁吃掉的"量出来（不能猜）

| 量具 | 位置 | 作用 |
|---|---|---|
| `op=perf`（只读） | `source/net/DebugControlServer.gd`（**已进受限白名单**） | FPS、10Hz 采样自身耗时 `sample_ms`（p50/p95/max）、观测请求耗时、**寻路查询计数**、节点/孤儿节点/内存 |
| 帧率随采样上报 | `_fast_state.fps` → runner `fast_scan.fps/fps_min` | 每局都留下"帧率 vs 单位数 vs 采样成本"的同一条时间线 |
| 探针 | `tmp_logs/campaign_accept/perf_probe.py <端口>` | 一行一秒地看：`fps / sample_ms / tactical_p95 / units / 寻路查询每秒 / nodes` |
| 连续性报告 | `AI_RTS/tools/continuity_report.py` 的 `perf` 段 | 验收报告直接打印"游戏自报帧率 p50/最低 + 采样耗时"（**观察项，不设门槛**） |

### 13.2 实测（隔离验收局，`with_ai=true, peaceful=true`）

| 端 | 单位数 | FPS | 10Hz 采样自身耗时 | 结论 |
|---|---|---|---|---|
| 客户端（渲染 + 面板 + DCS） | 53 / 68 / 91 | **116 ~ 120** | **p50 = 1 ms，max = 2 ms** | 观测通道 ≈ **1% 帧预算**，不是掉帧主因 |
| 专用服（无渲染，纯模拟） | 91 | **4 ~ 29**（波动） | 1 ms | **模拟本身**才是吃帧率的那一端 |

**结论**：副官通道（10Hz 采样 + 2Hz 观测 + 寻路闸门）在实测中是**廉价**的；游戏帧率的头号变量是**战场单位数**（模拟/RVO/寻路/渲染都随它线性涨）。
而单位数恰恰被我们自己的规则阶梯推高 —— 生产结算修好后 150 秒就有 105 个单位（无上限）。

### 13.3 修掉的三处真实开销（都会随规模放大）

| # | 问题 | 修法 | 依据 |
|---|---|---|---|
| ① | `is_target_reachable()` 是**每单位每 100ms 一次真寻路**（100 单位 ≈ 1000 次/秒，主线程） | 按单位名**哈希分槽**（每单位每 ~400ms 一次）+ 每采样硬上限 8 次（`REACHABILITY_STAGGER` / `FAST_REACHABILITY_MAX_PER_SAMPLE`） | `path_failed` 最坏发现延迟 200ms→~800ms，可接受 |
| ② | `CollectingResourcesWhileInRange` 对 Unit_2/3 **逐采集 tick 打印** `[COLLECT]` | 删除该打印 | 单局刷 **35 万行** stdout + 每次一次 `units_adhere` 计算 |
| ③ | 面板 `AdjutantButton._own_unit_names()` 的调试判据写成 `_attach_debug_left >= 0` | 改**会递减**的预算 + 结果 **1 秒缓存** | `0 >= 0` 恒真 → **每次调用**都打带回溯的 `push_warning` 并同步问一次全量 `fast_state`（日志实测成片出现） |

（更早一条：**重烘期不发求生寻路查询**，`movement.nav_revision_changed`，见 §10。）

### 13.4 兵力上限（手册 04 §军队规模规划，此前从未真正执行）

- **依据**：手册"接敌前坦克上限 **60**；达到上限停止产坦克，资源留给战损重建"，
  并把"**无上限生产**"列为禁止项（v4 实测 385 辆坦克既调不动也拖垮端点）。
- **实现**：`rules_fallback.COMBAT_UNIT_CAP = 60` +
  `combat_units()`（**已落地 + 队列中**，两者都算）/ `combat_production_allowed()`（达到即**记账后拒发**）。
  接在**阶梯 2** 与**并行填充的生产轨**两处（同一函数、同一口径）；工人/建造/防御**不受影响**。
- **留档**：`state["army_cap"] = {cap, deployed, queued, blocked(按轮次计数), last_block_tick}`
  → 进 checkpoint（**已验证**：checkpoint 里出现该字段）、进 `state.summary()`。
  `agent_runner` 的"每轮档案记录"也已接入该字段，**并已真机验证**（§15 修掉两个埋点 bug 之后）：
  `archive_0cc331c0/rounds.jsonl` **27 行、每行都带 `army_cap`**，同一档案里
  `events/rounds/commands/decisions` 五条流水齐备。
  这样"这一轮为什么没有出兵"在归档里有两种可分辨的解释：**达到上限（设计）** 还是 **没轮到（故障）**。
- **守门测试**（`tests/test_rules_fallback.py::ArmyCapTest`，5 条）：
  到上限**必须停**、差一个照常出、**队列中的也算**、工人产出不受限、`blocked` 按**轮次**计数（同轮阶梯+填充各判一次只 +1）。
- **真机观察**：cap2 局 150s 时我方 **72 个单位 = 46 士兵 + 14 坦克 = 作战单位正好 60**（上限生效），
  另有 6 工人 / 5 建筑 / 1 无人机（工人与建筑未被上限波及）。

### 13.5 本轮暴露的两个环境/工程问题（照实记录，未掩盖）

1. **同一个权威口上同时挂着两个 runner**（实测 pid 42468 与 31684 同时在 24592）：
   面板会把上次用过的权威口写进 `user://adjutant_local.cfg`，于是**验收那一局**可能被面板的
   runner 一起指挥 —— 两边各自下发命令、各自写 checkpoint，成绩不可复现且来源不明
   （这也解释了某些 checkpoint 里**没有**新字段：是另一个更旧的 runner 写的）。
   → 已在 `campaign_accept.py` 加**拒跑闸门** `foreign_runners()`：开跑前扫"命令行里带同一权威口的
   agent_runner"，有就**直接拒跑**并打印清理办法（`taskkill /PID <pid> /F`）。
2. **服端在对局中途退出**（24592 `ConnectionRefused`，客户端仍 120FPS 存活）；
   退出前只有"单位离开场景树时 `NetSession` 已释放"的收尾噪音，**没有**崩溃栈。
   已有的对照：**不挂 runner** 的同配置局，服端 **180 秒全程存活**（`tmp_logs/campaign_accept/server_alive_probe.py`）。
   但挂 runner 的局也在别的时段跑满过 240 秒 → **样本不足，不能据此判定因果**。
   复现步骤：`python tmp_logs/campaign_accept/server_alive_probe.py`（无副官对照）
   ↔ `python tmp_logs/campaign_accept/short_match.py 300 off <tag>`（有副官），各跑 2~3 次比对。

### 13.6 下一步（按性价比）

1. **兵力上限的真机长局复验**（本轮因上一条的服端退出未取到干净长局）；
2. **"有/无副官"各 2~3 局的对照**，把服端中途退出定性（副官相关 / 环境固有）；
3. 若帧率仍随规模下滑：把 `COMBAT_UNIT_CAP` 与玩家偏好（"少而精 / 多而杂"）绑定，并在面板显示当前兵力/上限。

---

## 14. 当日自审（2026-09-13 收工前，用户："把今天的工作检查一下"）

### 14.1 当场修掉的两处（评审发现 → 立即修 → 已验证）

| # | 发现 | 性质 | 处置 |
|---|---|---|---|
| ① | `test_retired_token_absent_from_tracked_files` **全天红**，而我一直把它当"既有自指失败"带过 | 守卫**自相矛盾**：要搜"旧 token 不得出现在 tracked 文件"，却把该 token 以**字面量**写在它自己和两个同步守卫里（`AdjutantCredentialSmokeTest.gd`、`tools/server_healthcheck.py`）→ 永远失败 | 三个夹具改为**非字面量拼接**（值不变、语义不变、明文不进日志/对话）→ 该守卫转绿；**全量单测 664 条 0 失败**（今天第一次全绿） |
| ② | 面板 `AdjutantButton._own_unit_names()` 的调试判据写成 `_attach_debug_left >= 0` | `0 >= 0` 恒真 → **每次调用**都打一条带 GDScript 回溯的 `push_warning`，并同步问一次全量 `adjutant_fast_state`（面板跑在游戏进程里，直接吃玩家帧率） | 改成会递减的预算 + 结果 **1 秒缓存**（见 §13.3 ③） |
| ③ | `AdjutantRulesExportSmokeTest` 2 条红：硬编码"11 种实体 / 5 条生产定义" | 配置 09-12 已扩到 **14 种实体 / 8 条生产**（新增 `transport_truck`/`apc`/`heavy_tank`）→ 断言长期为红，与"配置驱动"的本意相反 | 期望值改为**从配置派生**；新增两条守卫（导出必须覆盖全部类型、必须存在"能打但不能动"的固定防御）→ **0 失败** |
| ④ | 作战单位口径有**三份硬编码副本**（`rules_fallback` / `behavior_tree` / `campaign`） | 漏 `apc`/`heavy_tank`；`behavior_tree` 那份还写着配置里**不存在**的 `vehicle`/`aircraft`（直升机漏计） | 统一为**一处派生**（`attack ∧ move`）+ 落档 `state["combat_types"]`，详见 §14.6 |

### 14.2 记录在案但**未修**（需要判断或成对实验）

| # | 发现 | 影响 | 处置 / 建议 |
|---|---|---|---|
| ① | 权威口上出现过**两个 runner**（面板配置记住了上次用过的验收端口） | 同一局被两方指挥：命令重复、档案互踩（那两局的 `rounds.jsonl` 直接没生成） | 已加**拒跑闸门**；根因（`_remember_authority_port` 把"测试端口"写进玩家配置）仍待修 |
| ② | 服端在对局中途退出（24592 `ConnectionRefused`） | 验收局无法跑满时长；真实联机局若复现=严重 | 已写成对对照实验 `ab_server_exit.py`（两臂配置相同，唯一差别 = 副官在不在），见 §14.7 |
| ③ | 文档 §7 一直写"607 条 / 1 条失败"，而实际早已是 664 条 | 文档与代码脱节（同日多次改动没回头改数） | **已修**：改为"670 条 0 失败"并把 token 守卫的处置写清 |

### 14.3 未提交与工作区状态（溯源用）

- 工作区**未提交**（按约定）：28 个已跟踪文件改动 + 一批新增文件（`deploy/match_archive.py`、
  `tests/test_continuity_report.py`、`tests/test_match_archive.py`、`tests/test_e2e_fixture.py`、
  `tools/continuity_report.py`、`tools/log_inventory.py`、`tools/archive_match.py`、
  `tools/archive_index.py`、`tools/production_report.py`），合计 **+2873 行**。
- 新增工具**逐个冒烟**：5 个复盘工具在不给参数时都给出清晰用法（没有堆栈）；
  `archive_index.py` 在当前档案根生成索引：**14 局 / 完整 7 局**。
- 本机**无残留进程**（验收端口与 runner 已清）；测试机上的 Godot 进程均为玩家会话或 MCP。

### 14.4 清理时**误删**了验收脚本（如实记录）

收工清理"今天新建的一次性脚本"时，按"今天创建 = 一次性"的规则删了 22 个文件，
其中 **`player_takeover.py` 是被文档引用过的**（§4.6 的"玩家接管真机 60+45 秒"，
以及 §11.3 的 `test_outnumbered_retreat_...` 系列真机复核）；另外 9 个
（`verify_panel.py` / `panel_criterion.py` / `probe_nav.py` / `read_campaign.py` /
`accept_state.py` / `plan_report.py` / `fix_e2e_balance.py` / `clean_ports.py` / `costs.py`）
文档未引用、影响有限。磁盘上没有副本，**不可恢复**。

- 仍然有效的保障：玩家接管的**行为**由 `tests/test_player_interrupt.py` 与
  `tests/fixtures/replay_player_takeover.jsonl` 在单测层钉住（今天 664 条全绿），
  真机结论与截图仍在 §4.6 与对应档案里（证据没丢，丢的是"再跑一次"的脚本）。
- 复现那局的做法（改用现有骨架，不必再写新脚本）：`short_match.py` 起局 +
  `CA.start_runner(...)` 起副官 → 用游戏自己的 DCS `op=move`（`as_player`）对某个
  已被副官接管的单位下一条**玩家命令** → 断言：该单位出现 `player_override` 事件、
  副官对应意图被丢弃且租约释放（口径见 §4.6 表格）。
- 教训（写进纪律）：清理脚本**不许按"文件创建日期"判一次性** —— 应按"是否被文档/流程引用"
  判定；被引用的文件要么保留、要么先搬进版本库再清。

### 14.5 本轮复核实际跑过的命令（都可重跑）

| 命令 | 结果 |
|---|---|
| `python -m unittest discover -s adjutant_coordinator/tests`（`source/` 下） | **664 条 / 0 失败**（6 skip） |
| `godot --headless --path AI_RTS res://tests/automated/AdjutantCredentialSmokeTest.tscn` | **11 PASS / 0 失败**（含"旧 token 不在客户端源码里"） |
| 同上，`AdjutantObservationSmokeTest.tscn` | **0 失败** |
| 同上，`AdjutantCommandProtocolSmokeTest.tscn` | **0 失败** |
| 同上，`AdjutantRulesExportSmokeTest.tscn` | **2 失败**（见 14.2 ⑤） |
| `godot --headless --check-only --script <改动过的 .gd>`（3 个文件） | 无 Parse Error（`NetSession`/`Utils` 的报错是 autoload 不在独立模式下的已知现象） |
| 5 个复盘工具**不带参数**运行 | 都给出清晰用法（无堆栈）；`archive_index.py` 生成索引：**14 局 / 完整 7** |
| `probe_fast.py <端口>` / `perf_probe.py <端口>` | 对活着的对局读到 `fps / units / sample_ms / 寻路查询数` |

### 14.6 作战单位口径统一（§14.1 ④ 的落地）

**问题**：同一件事（"谁是作战单位"）有三份硬编码副本，各自腐烂：

| 位置 | 原值 | 毛病 |
|---|---|---|
| `rules_fallback.COMBAT_TYPES` | `soldier/tank/helicopter` | 漏 `apc`（带 `apc_autocannon`）与 `heavy_tank` → 兵力上限少算、军事轨不指挥它们 |
| `behavior_tree.micro_parts` cfg | `soldier/vehicle/tank/aircraft` | `vehicle`/`aircraft` **配置里不存在** → 直升机（真实 id `helicopter`）漏计，影响树里的接敌/撤离判据 |
| `campaign._facts` | 又抄一份常量 | 注释还写着"与 rules_fallback 同口径"——口径分叉的现场 |

**处置**：唯一实现 `rules_fallback.combat_types_from_rules(rules)` =
`capabilities.attack ∧ capabilities.move`，由 `node_ingest` 每轮派生一次写进
`state["combat_types"]`（显式字段 + checkpoint + 档案），其余模块**只读**那一个字段，
读不到才回退常量（保守，行为不变）。

**真机导出实测**（`AdjutantRulesExportSmokeTest` 打印，14 种实体全部带 `capabilities`）：

```
能打的类型      = [anti_air_turret, anti_ground_turret, apc, heavy_tank, helicopter, soldier, tank]
可机动（=兵力）  = [apc, heavy_tank, helicopter, soldier, tank]
不可机动（防御） = [anti_air_turret, anti_ground_turret]
```

**为什么必须同时要 `move`（本轮新发现的坑）**：只认 `attack` 会把**固定炮塔**算成兵力 ——
60 座炮塔就能吃满兵力上限（部队再也补不了兵），军事轨还会给炮塔派 `attack_move`（它不能动）。

**守门**：
- Python：`CombatVocabularyTest` 6 条（派生集合正确 / 炮塔不算兵力 / 残缺输入不派生 /
  `state` 字段优先 / APC 只在派生口径下计入上限 / 缺能力字段回退常量）；
- 游戏侧：`AdjutantRulesExportSmokeTest` 增两条 —— "每个类型都必须带 capabilities"
  与"必须存在能打但**不能动**的固定防御"（否则派生口径会静默退化或把炮塔当兵）。

### 14.7 对照实验：服端中途退出到底和副官有没有关系（§14.2 ② 的执行）

- 脚本：`tmp_logs/campaign_accept/ab_server_exit.py`
- 设计：**两臂的对局配置完全相同**（`with_ai=true, peaceful=true`），唯一差别是
  副官 runner 在不在；两臂交替各跑 N 次（交替是为了让机器负载漂移不偏向任一臂）；
  每 10 秒记录服端（24592）/客户端（24590）存活。
- 结果落 `tmp_logs/langgraph_recon/campaign_accept/ab_server_exit.json`，并打印汇总表。
- 判定：`runner` 臂显著更容易中途退出 → 与副官相关（继续查命令/事件）；两臂相当 →
  环境固有（改查游戏侧或联机链路）。

**本轮已取到的样本（样本少，如实标注）**：

| 局 | 游戏自带 AI | 副官 runner | 服端(24592) | 客户端(24590) |
|---|---|---|---|---|
| 早先对照（`server_alive_probe.py`，180s） | 关 | 无 | **全程存活** | 存活 |
| 本轮对照（同脚本，202s） | **开** | **无** | **120s 后死亡** | 存活（120FPS） |
| cap3 / cap4（`short_match.py`） | 开 | 有 | **60~90s 死亡** | 存活 |
| f1a~f1d / p1a~c / f2c2（更早） | 开 | 有 | 存活满时长 | 存活 |

**结论（只到证据支持的程度）**：**不能归因于副官** —— 一次"游戏 AI 开着但完全没有副官"的局，
服端同样在约 2 分钟后退出。也就是说这个症状在**没有副官**的情况下就能复现，
方向应转向**游戏侧/起局侧**（服端进程为何结束：主动 `quit` 还是被谁收掉）。
已在所有服端日志里搜索 `victory/defeat/结算/MatchEnd/quit/shutdown/退出` 等关键词 ——
**零命中**，说明它退出时**没有留下任何原因**（既不是崩溃栈，也不是显式的收局日志）。

**下一步（属游戏/起局侧，不在副官职责内）**：
①在服端进程上挂退出钩子（`NOTIFICATION_WM_CLOSE_REQUEST` / `_exit_tree`）打印调用栈；
②看 `campaign_accept`/`restart_local` 的收尾逻辑里有没有"按端口/按父进程"的清理会误伤服端；
③若确认是对局结算导致的正常关服，把它写进验收脚本的预期（而不是当失败）。

---

## 15. 第二轮真机复验：抓到我自己的两个埋点 bug（2026-09-13 收尾）

**为什么要复验**：上一轮改动里新增了若干"只加看、不改行为"的埋点。真机一跑就暴露：
**埋点写错名字 → 被外层 `except` 吞成 `tick_error`/`archive_error` → 同轮后面的记录整块消失**。
两处都不是逻辑错误，而是"顺手写错变量"，代价却是复盘证据缺块。

| # | 症状（真机实测） | 根因 | 影响 |
|---|---|---|---|
| ① | `scan_hz = 0.00`、`fps p50 = None`、`tick_error` **186/186 轮** | 扫描埋点引用了不存在的 `scan_stats`（真名是 `self._last_scan_stats`）→ `NameError` | 同轮后面的留档 / 决策 / HUD / 回执**全部被跳过** |
| ② | 档案里只有 `decisions.jsonl`，**从来没有 `rounds.jsonl`**（MANIFEST 只能写"runner 未写留档"） | `_archive_round` 的 `intents` 字段用了**下面才赋值**的 `live_intents` → `UnboundLocalError` → `archive_error` ×21 | 每轮"世界事实"（余额/单位/敌情/生产队列/扫描指标）整条流水**从未落盘** |

### 15.1 修复（三件事，都带"以后不许再犯"的护栏）

1. **埋点独立包一层**：扫描埋点整段放进自己的 `try/except`，出错只记 `scan_log_error`，
   **绝不牵连**同轮的决策/HUD/留档；`live_intents` 提到 `_archive_round` 开头绑定。
2. **档案行缓冲**（`buffering=1`）：留档不许依赖优雅退出 —— 验收/收尾用
   `taskkill /F` 收 runner，默认 8KB 缓冲下"已写的行"还在内存里，进程一被强杀就**整份丢**。
   守门：`test_match_archive.test_lines_hit_disk_before_close`（**没有 close 也必须已落盘**）。
3. **静态守门** `tests/test_use_before_binding.py`：AST 扫全部副官模块，禁止
   "用到一个名字、但它的第一次赋值在更下面"（就是上面 ② 的形状）。
   它会先自证能抓到该形状，再扫真代码（当前 **0 命中**）。

**全量单测 675 条 / 0 失败。**

### 15.2 本轮取得的真机事实（cap5~cap8）

| 事实 | 数值 | 说明 |
|---|---|---|
| **游戏自报帧率** | **p50 = 22、最低 = 1**（cap7） | **首次在真机上量到用户说的"20-30FPS"**；同一局 10Hz 采样耗时 **p50 = 2ms / max = 2ms** → **观测通道不是掉帧原因** |
| 当时的单位规模 | 46 → 73 | 与服务端模拟负载一致（§13.2 已测：服务端 4~29FPS、客户端 116~120FPS） |
| 面板调试刷屏 | `[ADJ-DBG] fast_state` **恰好 3 次**（修复前是"每次调用都打"） | §14.1 ② 的面板修复**真机确认** |
| 污染自证字段 | `foreign_runners=[]`、`server_died_at_s` 可读 | 验收报告现在会**写明**"本局是否有第二个 runner"（本轮实测确实抓到过一次：pid 10920 与 52464 同挂 24592） |
| 服端中途退出 | 已排除副官（§14.7） | 本轮又见 1 次超时（cap6 t=60s 后自愈）与 1 次 22 秒静默（cap6） |
| 游戏侧报错 | `Invalid access to property or key 'navigation_map_rid'` ×5（cap7） | **游戏侧导航问题**，与副官无关；另一路会话的复盘计划里已记录同一条 |

### 15.3 档案链路修复的**真机确认**（cap8 / cap9）

| 局 | 档案 | 事实 |
|---|---|---|
| cap8 | `archive_0cc331c0` | **`rounds.jsonl` 27 行，每行都带 `army_cap`**；五条流水齐备（rounds/events/commands/decisions + MANIFEST/SCHEMA/digest）→ §13.4 的"进档案每轮记录"从**未验证**变为**已验证** |
| cap9 | `archive_8f00699f` | `rounds.jsonl` 15 行，**每行带 `fps` 与 `sample_ms_p50`**（新增）→ 任何一局都能直接回答"**帧率 vs 单位数 vs 副官开销**"，不必再翻 runner.out |

（`fps` / `sample_ms_p50` 是这一轮为"掉帧归因"专门加进每轮档案的；样例：
`tick=749 fps=43 sample_ms_p50=2.0 单位=4`。）

### 15.4 10 分钟压力局（用户："这个阶段没必要 1 分钟快速测，可以测 10 分钟压力局"）

**两次 600 秒压力局（敌人 AI 正常进攻，不再 peaceful）都在 ~100 秒被"服端自己退出"掐断**，
但**在被掐断之前拿到的数据已经回答了两个关键问题**（档案 `archive_e4329752`，162 轮）：

| ① 帧率 vs 规模（同一局内的真实相关） | ② 副官通道开销（同局每秒都在量） |
|---|---|
| ≤40 单位：fps 均值 **108.2**（n=86） | 10Hz 采样耗时 **恒为 1.0ms**（全程） |
| 41-70 单位：fps 均值 **60.0**（n=56） | 观测请求 p50 ≈ 10~18ms |
| **>70 单位：fps 均值 29.2**（n=20） | 全局 fps：min 11 / p50 96 / max 121 |

→ **掉帧是"单位规模 → 模拟负载"造成的，与副官通道无关**（这条以前只有单点证据，现在是整局相关曲线）。
→ 也解释了用户那句"20-30FPS"：**单位数上到 70+ 时，20~30FPS 就是这台机器的真实表现**。

**③ 真实交战下的受阻降级（此前一直标记"未验证"）—— 实测在动**：
`retreat` 60 次、`hold` 17 次、`wait` 6 次（`rounds.jsonl` 的 `movement.fallbacks` 逐轮可查）。
也就是说 §10 的"被拦住之后必须有归宿"在**敌人主动进攻**的局面下确实生效。

**④ 兵力上限在这局没有触发**（`army_cap` 全程 `{}`，我方峰值 72 单位）：
真实交战中我们的单位会被打掉，作战单位没到 60；上限只在"和平/暴兵局"里才会咬合 ——
而 FPS 问题恰恰出在那种局（早先 peaceful 局 150 秒就 105 单位）。**结论：上限方向正确，但只在暴兵局起作用。**

### 15.5 本轮顺带修掉的**并行会话端口冲突**（10 分钟局跑不下来的直接原因）

口径表原来**只允许 24589 一个基端口** → 两路会话必然互抢：实测抓到"两个 runner 同挂 24592"、
两边都按端口清理 **互相杀**（我的压力局 runner 就是这么被掐死的）。
处置（`config/dev_ports.json` + `dev_ports.py` + 守门测试）：

- 验收段扩成两段：默认 **24589-24592**，并行会话 **24609-24612**（`acceptance_parallel`）；
- `acceptance_blocks()` 返回全部合法段，`check_acceptance_base()` 对**任一段**放行（越界仍拒跑）；
- 新增守门：并行段角色必须落在自己段内、且与玩家/面板段不重叠（全量单测 **676 条 0 失败**）；
- 工具：`tmp_logs/campaign_accept/isolate_my_run.py`（只杀**外来** runner、留本局自己那个，
  `venv` 路径即"自己人"标记）。

### 15.6 服端"自己退出"的现场证据（交给游戏侧的那一步）

在 `Globals.gd` 加的 `[EXIT-TRACE]` 命中了，**这是本轮最有价值的游戏侧线索**：

```
[EXIT-TRACE] EXIT_TREE：场景树收尾（tick=6048）
[EXIT-TRACE] PREDELETE：引擎收尾（Globals 释放，tick=unknown）
```

补一局（stress3，300 秒）把追踪增强后（带上"退出那一刻的场景与对局结果"）再取一次：

```
[EXIT-TRACE] EXIT_TREE：场景树收尾（tick=5515，场景=unknown，对局结果=无该节点）
[EXIT-TRACE] PREDELETE：引擎收尾（Globals 释放，tick=unknown）
```

- `场景=unknown` ⇒ 退出那一刻 `current_scene` **已经是空**（场景树先被拆了）；
- `对局结果=无该节点` ⇒ 树里**已经找不到** `MatchOutcomeRuntime`；
- 两次的 tick 都在 5500~6050（≈92~101 秒），**高度一致** → 像是一个**固定时长的收尾路径**，
  而不是随机崩溃。

- `tick=6048`（60tps ≈ 100 秒）与"60~240 秒随机退出"的观测一致；
- **是引擎正常收尾**（不是崩溃栈、也不是 `/F` 强杀 —— 强杀不会有这两行）；
- 退出**前**的日志只有：`意图登记已满/幂等账本已满，淘汰最早记录`（我们的有界账本按设计淘汰）、
  以及单位离开场景树时的 `NetSync.broadcast_presentation → rpcp` 报错（收尾噪声）；
- 全仓 GDScript/C# 里**没有**对局期间可达的 `quit()`；日志里也**没有**任何收局/胜负信息。

→ 结论：**有人在对局中途让引擎正常退出**（游戏侧），不是副官、不是消息通道、不是崩溃。
下一步（游戏侧，建议交给对应会话）：在 `SceneTree` 层挂退出原因（例如把所有 `quit()`
调用改成走一个带 `push_error` 的封装，或在 `MatchEndHandler`/`CampaignController` 里加埋点），
按 `tick≈6000` 这个时间点回溯触发者。

### 15.7 仍未解（如实）

1. **兵力上限的长局真机复验**：本环境里对局常在 60~130 秒失去服端或整体卡顿（游戏自报 1 FPS），
   拿不到"兵力稳定在 60"的干净长局。已有的证据是：单元级 17 条守门 + 早先 cap2 局
   150 秒时**作战单位正好 60**（46 士兵 + 14 坦克）。
2. **`state["combat_types"]` 在验收局为空**：说明那局的规则视图**没有** `capabilities`
   （或观测里没有规则视图）→ 派生不生效、回退常量（行为不变，但"配置驱动"在验收局**未验证**）。
   要坐实：在验收局里落一份规则视图的 `capabilities` 覆盖率（可在 `rules` 事件里加一次打点）。
3. **服端退出的最终归属**：已证明"与副官无关"，但**谁**让它退出的仍未定（无 `quit()` 可达、
   `/F` 杀不会留下收尾日志、日志里零关键词命中）。已在 `Globals` 加了 `[EXIT-TRACE]`
   （`WM_CLOSE_REQUEST` / `EXIT_TREE` / `PREDELETE` 三类，只打印不改行为），下次复现即可分辨
   "引擎收尾"与"外部终止"。
4. **本机有**另一路会话**在用同一批验收端口**（24589-24592）：本轮实测抓到"两个 runner 同挂
   24592"（pid 10920 + 52464），验收报告现在会记录 `foreign_runners` 把这个事实留档。
   两边都会按端口清理 → **互相杀**。建议：并行会话改用不同的验收基端口段，
   或让 `acquire_accept_lock` 把"端口段占用"写进锁内容并拒绝交叉。

---

## 16. 命令纪律（2026-09-14 用户："你下达命令不能瞎下达啊，部队还没到位你就下下一个命令"）

### 16.1 先把用户看到的现象量出来（档案是唯一真相）

用 `commands.jsonl`（真正下发给游戏的命令流）量，**修正过两次口径**（第一版把"同一意图的
意图级 + 命令级两条记录"当成冲突，数字虚高一个量级）：

| 指标 | 实测（修复前） | 说明 |
|---|---|---|
| "同 tick 同单位**不同命令**" | 每局 3~57 组 | 其中绝大多数是**一条被拒 + 一条被采纳**（不算真冲突） |
| "同 tick 同单位**两条都被采纳**" | `archive_045ed0d6` **1 组** | 现场：`fallback-hold-Unit_23-7`（→stop）与 `bt-retreat-Unit_23-2249`（→move）**都 Accepted** |
| **命令被拒比例** | **36%**（347 条里 124 条拒）/ 30% / 21% | 拒因**单一**：`当前武器无法攻击该目标所处的域（地面/空中不匹配）` |
| **同一 (单位,动作) 反复被拒** | `e4329752`：**112** 条命令属于"被拒≥3 次"的 (单位,动作) | 最极端 `Unit_43 attack` **被拒 10 次**（≈每 15 秒重试一次，正撞 `ORDER_REPEAT_WINDOW_TICKS`） |

→ 用户看到的"瞎下达/部队跟不上"，由三件事共同造成：**半路换目标**、**同轮自相矛盾的两条命令**、
**反复重发注定被拒的命令**。

### 16.2 三条修复（都收在唯一咽喉处，都有守门测试）

| # | 修复 | 收口位置 | 关键判据 |
|---|---|---|---|
| ① | **在路上的不许换目标**（到位再下一条） | `nodes._gate_movement` + `movement.hop_in_progress` | 路线 `ok=True`（= 已批准且未到达/未作废）→ 复用**当前中继点**，即使本轮算出来的目标已经变了；到达/路径失败/遇敌/换网格才允许换；`HOP_HOLD_MAX_TICKS=1800` 防"卡在陈旧路线"；被压下的目标记 `hop_hold` + `movement_stats.hop_holds` |
| ② | **一个单位一轮只许一条"去哪/停哪"的命令** | `nodes._resolve_same_unit_conflicts`（在**校验与预算之后**） | 移动族内按既有 `ACTION_PREEMPT_RANK` 取舍（求生 90 > 交战 70 > … > 守卫 10），同档取先发的；被压下的走既有 `intent_dropped`（`same_unit_conflict`） |
| ③ | **打不了的目标不再派**（换目标，而不是重发） | `placement.REJECT_TARGET` + `nodes._apply_receipt_to_state` + `rules_fallback.attackable_enemies` / 行为树 `_attackable` | 权威回执的"武器域不匹配"→ 记 «单位×目标»（`state["unattackable_targets"]`，`TARGET_BAN_TICKS=1800`，有界 256）；出击/交火选目标时剔除 |

**②踩过的坑（如实记）**：第一版把去重放在**校验之前**，结果把"攻击已死目标"（rank 70）留下、
把有效的"重新定位"（rank 30）丢掉 → 前者随后被 `target_dead` 拒掉，**两个都没发**。
回放夹具 `replay_target_dead.jsonl` 当场抓住（这正是它的价值）→ 改成**只在校验通过、预算通过
之后的意图之间**裁决。另：`action_rank()` 对未知动作返回 100（那是"抢不抢旧任务"的口径），
同批去重里必须按**最低**处理，否则会"未知动作压过求生"。

### 16.3 真机复验（`fix1` 局）与遗留

真机局同样被服端自退（§15.6）掐断，但三条修复都已由守门测试钉住（命令纪律 5 条 + 目标记忆 10 条 +
hop-hold 6 条），并可从档案继续量：`measure_flip.py` / `measure_conflicts.py` / `measure_rejects.py`
（三者都在 `tmp_logs/campaign_accept/`，口径写在各文件头部）。

**仍要做的**：① 把"拒绝率"与"同 tick 冲突"接进连续性报告（现在是三个独立量测脚本）；
② `attack` 大量被拒的**上游**原因（为什么我们总在挑打不了的敌人）—— 现在靠拒绝反馈学习，
更根治的是**用规则视图里的域信息在选目标时就排除**（需要确认导出里空中/地面域字段）。

### 16.4 ⭐根因：图通道漏声明，新字段每轮被静默丢掉（本轮最后才发现）

上面三条修复写完、单测全绿，真机却发现"目标记忆恒空、拒命令照旧刷屏"。最后定位到
`graph.GraphStateDict` —— LangGraph 引擎在图入口用 `_cleaned()` 把状态**过滤成只含声明过的通道**，
而 `AdjutantGraphState` 有 **5 个字段漏声明**：

| 漏声明字段 | 真机表现（**此前都被误判过**） |
|---|---|
| `production_ledger` | 归档里"生产样本 0"（被当成"生产没发生"） |
| `army_cap` | 兵力上限留档永远空（**拦截本身有效**，因为它每轮从观测重算 → §13 的真机结论仍成立） |
| `combat_types` | 作战单位口径表恒空 → **曾被误判成"验收局的规则视图没有 capabilities"**（实测导出是齐的，见 §16.5） |
| `unattackable_targets` / `enemy_types` | **"打不了的目标"记忆每轮清空** → 同一条注定被拒的攻击命令每轮重发（`Unit_43` 被拒 10 次、一局 124 条被拒命令的真因） |

**修法**：五个字段一次补齐声明；新增**双向守门测试** `tests/test_graph_state_channels.py`：

- 正向：`AdjutantGraphState` 每个字段都必须在 `GraphStateDict` 里声明（漏了就红灯）；
- 反向：通道里声明了却既不是状态字段、也不在**临时交接键清单**里的 → 也是红灯
  （临时清单要逐条写清"为什么不需要进 checkpoint"）。

**全量单测 703 条 / 0 失败。**

**真机验证（`fix6` 局，96 轮）**：

```
target_memory 首: {'bans': 0, 'enemy_types': 0}
target_memory 末: {'bans': 64, 'enemy_types': 4,
                   'recent_bans': ['Unit_24|Unit_5', 'Unit_24|type:drone',
                                   'Unit_26|Unit_5', 'Unit_26|type:drone', ...]}
命令 157 条：Accepted 127（81%）/ Rejected 30
```

- 记忆**真的跨轮积累**了（首 0 → 末 64），且 `recent_bans` 一眼看出病根：
  **敌人 `Unit_5` 是 `drone`（空中）**，我们却反复派地面单位去打它 →
  权威每次回"地面/空中不匹配"；现在**按实体 + 按类型**都记住了。
- 命令接受率从修复前的 **64%/71%** 提到 **81%**（其余拒绝也被学进记忆，不再逐轮重试）。

### 16.5 顺带纠正一条此前写错的结论

§16.3 里我写过"`state["combat_types"]` 在验收局为空 → 说明规则视图没有 capabilities"——
**这是错的**：字段在 `_cleaned` 处被丢掉而已。实测（`probe_rules_caps.py` 直接问权威端）：

```
端口 24612 规则视图：类型 14 个，带 capabilities 的 14 个
  可机动能打（=兵力口径 attack∧move）: [apc, heavy_tank, helicopter, soldier, tank]
```

也就是**配置驱动的口径在验收局是生效的**（前提是通道声明补齐）。留一条教训：
**"字段读出来是空" 先怀疑"它有没有跨轮活下来"，再怀疑"上游有没有给"**
（两者在日志上长得一模一样）。

### 16.6 迭代记录（用户 2026-09-14："我希望你从测试反复迭代这件事"）

**先把迭代做成一条命令**：`tmp_logs/campaign_accept/iterate.py`
（跑一局 → 读 `continuity_report` 的 JSON → 追加 `iterate_log.jsonl` → 打印最近 N 局对比表）。
命令纪律四项也进了验收报告（`continuity_report.command_discipline`：接受率 / 同 tick 双发 /
重试浪费 / 拒因 / 目标记忆；其中"同 tick 两条都被采纳"是**硬判据**）。

| 迭代 | 改了什么 | 命令数 | 接受率 | 同tick双发 | 重试浪费 | 域不匹配 |
|---|---|---|---|---|---|---|
| fix6 | （基线：实体 + 目标类型拉黑） | 157 | 0.809 | 0 | 0 | 29 |
| it1 | 单位类型级拉黑（**但行为树那条路漏传 `own_unit_types`**） | 420 | 0.745 | 0 | 58 | 74 |
| it2 | 行为树补上 `own_unit_types`（类型键这才真正命中） | 212 | **0.925** | 0 | 3 | **8** |
| it3 | 记忆键进 dataclass/通道（账本这才跨轮） | 409 | 0.866 | 0 | 27 | 28 |
| it4 | 建造落点兜底过账本（不再返回基地坐标） | 495 | 0.877 | 0 | 34 | 21 |
| it5 | **升级退避**（900→1800→3600→7200）+ 模型菜单过滤 | 454 | **0.916** | 0 | **13** | 22 |

**迭代表明**：主指标（重试浪费）58 → 13、接受率 0.745 → 0.916；it5 的决策日志里能直接看到
`build_backoff level=2/3 (1800/3600 tick)` 与 `build_spot_exhausted ×11` —— **机制在按设计留痕**。

**迭代5 暴露的下一环（尚未修）**：it5 的建造拒绝里 **`OutOfBounds ×11`** 取代了
`SurfaceNotBuildable` —— 说明我们"界内"的几何模型与游戏侧对不上（很可能是
`map_bounds` 的坐标约定：游戏是**以中心为原点**还是以角为原点）。这是"瞎下达"的下一处。

### 16.7 ⭐迭代 2 暴露的第二类根因：**纯动态状态键**每轮归零（比 §16.4 更广）

只声明 `GraphStateDict` 通道还不够 —— **dataclass 之外**的纯动态键同样会被丢掉两处边界，
而它们的症状各不相同、极难归类（2026-09-14 it1 局实测）：

| 键 | 归零后的症状（都是历史上"讲不通"的现象） |
|---|---|
| `rejection_ledger` / `blocked_build_spots` | 坏建造点被拒 **12 次**（`spot_rejected.count` 恒 1，永远到不了"3 次拉黑"） |
| `recent_orders` | "已下发指纹"每轮清空 → 同一条命令可以**每轮重发**（重复下发的源头之一） |
| `congestion_until_tick` / `congestion_events` | 拥塞退避失效（历史上 527 条 `LedgerFull` 的成因之一） |
| `build_backoff_until_tick` / `build_reject_streak` | 连续失败计数每轮重来（全局退避几乎不触发） |

**修法**：7 个键成为 `AdjutantGraphState` 字段（随 `to_dict/from_dict` 往返）+ 图通道声明；
并把**静态扫描**加进守门测试：扫 `graph/*.py` 里 `state["x"] = …` / `state.setdefault("x", …)`
的字面量键，凡不在"通道 ∪ 状态字段 ∪ 显式临时键白名单"里的一律红灯
（白名单目前只有 `lanes_served_this_tick`：只写不读、跨轮无意义）。

**迭代 3** 即这一条的真机验证（指标见 `iterate_log.jsonl`）。

---

## 17. 帧率治理（用户 2026-09-14："后面游戏限制一下 60 帧吧，需要有动态优化机制，
##     单位多就降低渲染效果，能保持尽可能稳定 60 帧"）

### 17.1 设计：两条腿，缺一条都不稳

| 腿 | 信号 | 作用 | 为什么不能只有它 |
|---|---|---|---|
| **前馈** | **自己的单位数**（`controlled_units`） | 部队规模到门槛 → 画质**立刻**降到对应档（用户点名的那条） | 只靠它无法知道"这一档够不够" |
| **反馈** | 实测 **FPS**（低帧累积/高帧累积） | 真掉帧 → 降档试用；帧率稳 → 逐级升回 | 只靠它，掉帧已经发生（玩家已经卡了一下） |
| **效果验证** | 降档后盯 `VERIFY_SECONDS` | 帧率没回来 = 画质不是瓶颈 → **把画质还回去** | 没有它就会"白降"（2026-09-14 用户投诉的正是这个） |

- 落地：`source/PerformanceGovernor.gd`（autoload）+ `project.godot` 的 `run/max_fps=60`；
- 判据全在**纯函数** `step(core, sample)`：低帧门槛 `DOWNGRADE_FPS=50` 持续 `DWELL_SECONDS=2.5`
  才降、冷却 `CHANGE_COOLDOWN_SECONDS=3` 防"连跳两档"、升档 `UPGRADE_DWELL_SECONDS=6`
  **只看帧率稳不稳**（旧版要求 CPU 帧时 < 8ms → 这台机器实测 10.9ms，永远升不回去）；
  **升档不许越过部队规模要求的档**（前馈是硬门槛，见 §17.2 的测试）。
- 档位表（0 最高 → 3 最低）：渲染缩放 `1.0 / 0.9 / 0.75 / 0.6`、MSAA `2/1/0/0`、
  阴影（含阴影图集 `4096/2048/1024/512`，最低档直接关阴影）、SSAO/辉光/雾/SDFGI 逐档关、
  网格 LOD 阈值 `1.0/1.5/2.5/4.0`。
- **关掉能还原**：启动时快照原始渲染设置，`set_enabled(false)` 原样还原（绝不吞玩家的设置）；
  配置在 `user://performance.cfg`（`dynamic_quality` / `max_fps` / `down_fps` / `change_toast`）。
- **headless 专用服自动禁用**（没有渲染可调，也不该占 CPU）——服务器不参与画质治理。

### 17.1.1 二次定标（2026-09-14 用户："这么点单位就要低画质了"）

真机日志（用户截图那一局，客户端 `godot.log`）：

```
[PERF] 画质 → high（tier=1 scale=0.90 units=40 fps=60）原因=units=40
[PERF] 画质 → medium（tier=2 scale=0.75 units=70 fps=60）原因=units=70
[PERF] 画质 → low（tier=3 scale=0.60 units=80 fps=57）原因=fps=57     ← 锁 60 时 57 帧只是 5% 抖动
```

三个根因（都已修）：

1. **前馈口径错**：数的是 `units` 组 = **全图（含对手/电脑 AI）**。真机实测：全图 41 个单位里
   一大半是对面的，照样触发降档 → 改成只数 `controlled_units`（自己的兵），门槛 50/80/120。
   对面的兵带来真实负载时由**帧率那条腿**兜住。
2. **降档门槛太敏感**：`DOWNGRADE_FPS=57`（锁 60 时 5% 抖动就降）→ 改 **50**、持续 2.5s。
3. **升档不可达 → 只降不升**：旧版升档要求 `fps>59 ∧ cpu_ms<8 ∧ draw_calls<420` 连续 6 秒；
   实测这台机器 60 帧时主线程帧时 **10.9ms**、绘制调用 220 → `cpu_ms` 门槛永远不满足，
   降到"低"之后再也没回来（截图就是 60 FPS + 低画质）。→ 去掉 CPU/绘制调用门槛（只留迟滞+冷却），
   并加"降档效果验证"：降完 8 秒内帧率没回来就把画质还回去，且 60 秒内不再自动降。

### 17.2 可观测与守门

- 随每轮 10Hz 采样上报 `quality_tier` / `quality_scale` → runner 落档（`fast_scan.quality_tier_*`）
  → 连续性报告新增 **"帧率治理"** 段（画质档峰值/末值 + 最低缩放 + 单位数峰值）；
  `iterate.py` 的对比表也多一列"画质档"。
- `op=perf` 新增 `governor` 块（档位/缩放/上限/帧时/绘制调用/最近一次升降原因）。
- **冒烟测试** `tests/automated/PerformanceGovernorSmokeTest.gd`（已登记进
  `config/full_regression_suite.json`，id=`performance-governor`）：钉住
  ①单位门槛表（**只数自己的兵**）；②**单位多立刻降档**（用户点名行为）；③迟滞（且 57 帧不算掉帧）；
  ④冷却不许连降；⑤升档保守 + **不许升过部队规模要求的上限**；
  ⑥**升档不需要 CPU 余量**（回归用例：`cpu_ms=10.9 / draw_calls=220 / fps=60` 必须能升回去）；
  ⑦**降档必须换来帧率**（换不来就还回画质并记住 60 秒）；
  ⑧前馈只看自己的兵（对手的兵不算）；⑨**预热期不认帧率**（见 §17.3）。
  headless 直跑：`0 failure(s)`。

### 17.3 真机复验与踩到的坑（如实）

**帧率上限生效**（同一套验收脚本，之前 vs 现在）：

| 局 | 帧率 p50 | 说明 |
|---|---|---|
| fix6 / it1 / it2 / it3（未锁帧） | 112 / 40 / 96 / 85 | 不限帧时被渲染到 GPU 极限（功耗/风扇代价） |
| **perf60（锁 60 + 动态画质）** | **52** | 上限 60 生效；部队规模大时靠治理降画质顶住 |

**用户点名行为的真机证据**（`tmp_logs/dcs/client_campaign.out`）：

```
[PERF] 帧率治理已启动：上限 60 帧，动态画质=true
[PERF] 画质 → high（tier=1 scale=0.90 units=41 fps=56）原因=units=41
```

→ 降档发生在 **41 个单位**、原因是 **units=41**（前馈），不是"掉帧后才降"。

**踩到的坑（真机第一版就暴露）**：开局加载期帧率极低（实测 `units=0, fps=32`），
第一版把它当负载 → **一开局就白降两档**（`high` → `medium`）。
修法：`WARMUP_SECONDS=6`（启动/切场景后只认前馈、不认帧率），并把这条写成冒烟用例。
**结论：先看真机日志，再谈"机制设计对不对"** —— 纯逻辑测试全绿也挡不住这类问题。

**配套记录**：`rounds.jsonl` 每轮新增 `quality_tier`/`quality_scale`（与 `units`、`fps` 同一时间线）；
验收报告的"帧率治理"段给出画质档峰值/末值与最低缩放；`iterate.py` 对比表多一列"画质档"。

---

## 17. AI 小队编制（用户 2026-09-14："小队可以是步兵多一点，坦克 1-2 个就行，小队是给
## AI 去指挥的，玩家也会有另一套分组小队系统"）

### 17.1 先量，再改：旧口径在真机上长什么样

量测脚本 `tmp_logs/campaign_accept/probe_squads.py`（复刻 `_cluster_key` 口径 + 读档案意图）：

| 层面 | 旧口径实测（live 局 24612，43 个作战单位） |
|---|---|
| **派生分组** | 全在同一 20m 格 → **20 + 20 + 3 = 3 支**，队内**最大间距 22m**（比"一格"还宽） |
| **发令粒度** | 档案 `archive_5d6cdb0e` 133 个意图里 `attack_move` **69 条全是单单位**（`rule-fill-advance-Unit_XX-<tick>`）；**带多单位的意图 0 条** |

即"名义上一队（≤20 人）／实际 20 个单兵被派去同一个点" —— 没有队形、没有间距、没有协同，
与"坦克被邻车顶住"是同一个病根。档案侧的"发令粒度"结论也与 9-13 文档"本轮未出现多人小队"一致。

### 17.2 新编制（唯一实现在 `graph/squads.py`）

| 项 | 取值 | 依据 |
|---|---|---|
| 步兵上限 | `SQUAD_INFANTRY_MAX = 6` | "步兵多一点" |
| 坦克上限 | `SQUAD_TANK_MAX = 2` | "坦克 1-2 个就行"；**轮转分配**：先保证每队 1 个再补第 2 个 |
| 单执行者上限 | `MAX_UNITS_PER_ACTOR = 6 + 2`（**派生值**） | 不另写一个数 |
| 空中 | **不与地面同队**（`SQUAD_AIR_TYPES`） | 空中/地面是两套导航网格（`MatchConstants.gd` `enum Domain { AIR, TERRAIN }`；`Drone/Helicopter/Scout.tscn` `domain = 0` = AIR） |
| 进编队的两道闸 | ①在**作战口径内**（`rules_fallback.combat_types_from_rules`：能打 ∧ 能动）②`movement` 为真 | 防止把工人/建筑/固定炮塔编进小队（"让建筑移动"） |
| 口径外对象 | 按 **(格, 类型)** 各自成组（不编队、**不丢**） | 拿不准就不编队，保守方向 |
| 工人组 | `WORKER_GROUP_MAX = 20`（与战斗编成**解耦**） | 工人是集群语义，别把采集线按 6 人拆散 |
| 边界 | 本模块只编 **AI 的指挥单位**；玩家侧分组（`legacy_ai_squad_*`）**不读不写不复用** | 用户明示"玩家也会有另一套分组小队系统" |

**顺带修掉一个真问题**：旧 `_cluster_key` 把**单位类型并进集群键** → "同一格的坦克"与"同一格的步兵"
永远落在两个不同集群，**编成里根本不可能同时有坦克和步兵**（这才是"坦克步兵各走各的"的机制）。

### 17.3 真机验证（`squad1` 局，直接调生产代码，不复刻口径）

`tmp_logs/campaign_accept/probe_compose.py`：

```
权威口径：作战单位 = [apc, heavy_tank, helicopter, soldier, tank]
S1  0,0     8 个单位  步6 坦2
S2  0,0     8 个单位  步6 坦2
S3  0,0     1 个单位  步0 坦1        ← 坦克轮转分配后的尾数
S4  0,0|drone  1 个单位（口径外·各自成组）  ← 无人机不再混进地面小队
S5  0,1     2 个单位  步1 坦1
S6  1,0     3 个单位  步2 坦1
S7  1,0     8 个单位  步6 坦2
```

"20 人一坨"消失、坦克 1~2 个、空中单列 —— 与规格一致。

### 17.4 守门与遗留

- **守门**：`tests/test_squad_composition.py`（8 条：步兵为主/坦克轮转/上限 20 人不再一坨/
  空中不与地面同组/口径外类型各自成组且不丢/固定炮塔不进小队/设施与工人不进战斗小队/编组确定性）。
  **全量单测 723 条 0 失败。**
- ⚠**仍未做（下一步）**：编成目前只影响**执行者/引用表层**（`build_decision_frame`，模型路径与 actor 表）；
  **规则路径仍在逐单位发令**（`rule-fill-advance-Unit_XX-<tick>`）。要让玩家看到"部队按小队走队形"，
  还要做：①移动族**按小队发令**（一条命令带全队，触发既有 `movement.squad_hop`/`squad_scatter`）；
  ②目标点**分槽**（每单位一个槽位，按朝向/间距排开，避免全奔同一个信标）。
- **另发现一处待定夺（不在本次范围）**：把测试夹具 `graph_test_helpers.tactical()` 的
  `queue/gather/construct` 改成"按调用方透传"（更忠实于真实 `op=tactical`）后，
  `test_tactical_task_patch` 的两条**模型成功路径**用例会失败：**有工人时程序仍会补一条 `rule-build-*`**。
  这可能是 2026-09-12 改版"规则中台常驻产出 baseline"之后的**用例过期**，也可能是真的越权补动作 ——
  夹具不忠实把它掩盖了，需要单独定夺（本次已把夹具改回原状，不让它牵动本条主线）。
